#!/bin/bash
set -ex

# Check if the --repo parameter is provided
if [ "$#" -lt 2 ] || [ "$1" != "--repo" ]; then
    echo "Usage: $0 --repo <repository_url> [--clean]"
    exit 1
fi

ARCH=$(dpkg-architecture -qDEB_HOST_ARCH)

REPPREFIX_URL="$2"
REPO_URL_TI_DEB="$REPPREFIX_URL/debian-repos"
REPO_NAME="vyos-build"
REPO_URL="$REPPREFIX_URL/$REPO_NAME"
ROOTDIR=$(pwd)

. $ROOTDIR/.defs.mk

# Check if the --clean parameter is provided
CLEAN=false
if [ "$#" -eq 3 ] && [ "$3" == "--clean" ]; then
    CLEAN=true
fi

# Delete the repository if it already exists and --clean is specified
if [ -d "$REPO_NAME" ]; then
    if [ "$CLEAN" = true ]; then
        echo "Cleaning up existing repository $REPO_NAME."
        sudo rm -rf "$REPO_NAME"
        rm -f .filesystem.* # Also remove all intermediate targets
    else
        echo "Repository $REPO_NAME already exists. Skipping clone."
    fi
fi

# Clone the repository if it doesn't exist or was cleaned
if [ ! -d "$REPO_NAME" ]; then
    git clone -b psl-master --single-branch "$REPO_URL"
#    git clone -b vyos-build-jf --single-branch "$REPO_URL"
fi

# Copy package-build-iGOS/ to vyos-build/scripts/ now that it's there
SRCDIR=package-build-iGOS
DSTDIR=vyos-build/scripts/
if [ ! -d $DSTDIR/$SRCDIR ]; then
    echo "=== I: $0: Copying $ROOTDIR/$SRCDIR into $DSTDIR"
    cp -rf $SRCDIR $DSTDIR
    echo "These files were copied from $ROOTDIR/$SRCDIR" > $DSTDIR/$SRCDIR/README-PSL
    # Borrow the vyos-build build.py if package-build-iGOS had none
    BUILDPY=$DSTDIR/$SRCDIR/build.py
    if [ ! -f $BUILDPY ]; then
        echo "=== I: $0: Symlink VyOS build.py to $BUILDPY"
        ln -rvfs $DSTDIR/package-build/build.py $BUILDPY
    fi
    unset BUILDPY
fi

# Install build_flavor
cp -f $ROOTDIR/updates/arm64fs.toml $ROOTDIR/vyos-build/data/build-flavors/

#frr build fix need to be fixed up later on it the build process
export EMAIL="psleng@perle.com"

############## package-build
# This will populate ./vyos-build/scripts/package-build/
#TSK=package-build
#BLT=.filesystem.$TSK.built
#if [ ! -f "$BLT" ]; then
#    echo "=== I: $0: package-build.py $TSK BEGIN"
#    ./package-build.py --dir $TSK --include salt vpp \
#        ethtool telegraf owamp net-snmp frr frr_exporter isc-kea strongswan \
#        openvpn-otp aws-gwlbtun node_exporter blackbox_exporter \
#        podman ddclient dropbear hostap kea keepalived netfilter \
#        pmacct radvd isc-dhcp ndppd hsflowd pyhumps bash-completion \
#        udp-broadcast-relay libhtp
#    touch "$BLT" # build success
#else
#    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
#fi
############## package-build
# This will populate ./vyos-build/scripts/package-build/
TSK=package-build
BLT=.filesystem.$TSK.built
#
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: package-build.py $TSK BEGIN"
    ./package-build.py --dir $TSK --include salt vpp \
        ethtool telegraf owamp net-snmp frr frr_exporter isc-kea strongswan \
        openvpn-otp aws-gwlbtun node_exporter blackbox_exporter \
        podman ddclient dropbear hostap kea keepalived netfilter \
        pmacct radvd isc-dhcp ndppd hsflowd pyhumps bash-completion \
        udp-broadcast-relay libhtp
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
fi

############## package-build-iGOS
# This will populate ./vyos-build/scripts/package-build-iGOS/
TSK=package-build-iGOS
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: package-build.py $TSK BEGIN"
    # See .defs.mk for $IGOS_PKGS value.
    # It is autogenerated from the IGOS_PKGS setting in Makefile
    ./package-build.py --dir $TSK --include $IGOS_PKGS
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
fi

############## package-symlink-debs
# This will populate ./vyos-build/packages/ with .deb files
TSK=package-symlink-debs
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    # Symlink everything to the vyos-build/packages directory
    for a in $(find $ROOTDIR/vyos-build/scripts -type f -name "*.deb")\
             $ROOTDIR/ti-bdebstrap/*.deb
    do
        test -s "$a" || continue  # Skip zero length junk

        case "$a" in
        *libsnmp-dev_*64.deb)  # Needed for frr (despite -dev_ pattern)
            ;;
        *libvppinfra-dev*)  # Needed for vpp and vyos-1x
            ;;
        *vpp-dev_*64.deb)  # Needed for vpp and vyos-1x
            ;;
        *isc-kea-doc*)  # isc-kea insists on this
            ;;
        *-dev_*|*-dbg_*|*-doc_*|*-dbgsym_*)  # Unwanted general patterns
            continue
            ;;
        */_CPack_Packages/*.deb)  # .deb build artifacts (duplicates)
            continue
            ;;
        */accel-ppp_*.deb)  # Obsolete accel-ppp (replaced by accel-ppp-ng)
            continue
            ;;
        */hsflowd.deb|*/sflowovsd.deb)  # Not actually .deb
            continue
            ;;
        */salt-api_*.deb|*/salt-syndic_*.deb|*/salt-dbg_*.deb|*/salt-master_*.deb|*/salt-cloud_*.deb|*/salt-ssh_*.deb)  # Unwanted salt components
            continue
            ;;
        esac

        test -f "$a" || continue
        echo "Symlinking package: $a"
        ln -vrfs $a $ROOTDIR/vyos-build/packages/
    done
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi

############## ti-linux-firmware
# This will populate ./debian-repos/ and augment vyos-build/packages/
TSK=ti-linux-firmware
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    if [ "$BUILDTARG" = "x86_64" ]; then
        echo "=== I: $0: SKIP $TSK (target $BUILDTARG = x86_64)"
    else
        # this section needs some rework to clean up how this ti firmware is pulled.
        sudo rm -rf debian-repos

        # TI repos are flaky, so retries are needed
        for i in 1 2 3
        do
            git clone -b psl-master $REPO_URL_TI_DEB && { i=''; break; }
            st=$?
            sleeptime=$((i * 30))
            echo "warning: Clone $REPO_URL_TI_DEB failed (status $st); sleeping $sleeptime and retrying"
            sleep $sleeptime
        done
        test -z "$i" || { echo "fatal: Cannot clone $REPO_URL_TI_DEB, giving up"; exit 1; }

        cd debian-repos

        # Determine the Debian distro to use
        DEB_SUITE=$(python3 -c "import toml; print(toml.load('$ROOTDIR/vyos-build/data/defaults.toml').get('debian_distribution', ''))")
        if test -z "$DEB_SUITE"; then
            echo "=== E: $0: Cannot determine debian_distribution"
            exit 1
        fi

        sudo DEB_SUITE=$DEB_SUITE ./run.sh ti-linux-firmware
        cd ${ROOTDIR}
        if [ "$BUILDTYPE" = "bookworm-am64xx-evm" ]; then
            ln -vrfs debian-repos/build/$DEB_SUITE/ti-linux-firmware/*64*.deb $ROOTDIR/vyos-build/packages/
        elif [ "$BUILDTYPE" = "bookworm-am64xx-igos" ]; then
            ln -vrfs debian-repos/build/$DEB_SUITE/ti-linux-firmware/*64*.deb $ROOTDIR/vyos-build/packages/
        elif [ "$BUILDTYPE" = "bookworm-j7200-evm" ]; then
            ln -vrfs debian-repos/build/$DEB_SUITE/ti-linux-firmware/*j7200*.deb $ROOTDIR/vyos-build/packages/
        else
            echo "=== E: $0: Undefined BUILDTARG:BUILDTYPE ($BUILDTARG:$BUILDTYPE)"
            exit 1
        fi
        # end of section for rework
    fi
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi
cd ${ROOTDIR}


############## build-vyos-image
# This will populate ./vyos-build/build/
# The psleng.github.io git repo must be populated for this to work.
TSK=build-vyos-image
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"
    cd $ROOTDIR/vyos-build

    # PSL related keys needed within the chroot within the build container.
    # They get copied from here into the chroot.
    LB_ARCH=data/live-build-config/archives
    cp -f ../updates/psleng.key $LB_ARCH/psleng.key.chroot
    cp -f $LB_ARCH/vyos-dev.pref.chroot $LB_ARCH/psleng.pref.chroot

    if [ "$BUILDTARG" = "x86_64" ]; then
        BUILDFLAVOUR=generic
    else
        case "$BUILDTYPE" in
            bookworm-am64xx-igos)  BUILDFLAVOUR=igos-am64x-all ;;
            bookworm-am64xx-evm)   BUILDFLAVOUR=igos-am64x-evm ;;
            bookworm-j7200-evm)    BUILDFLAVOUR=igos-j7200-evm ;;
            *) echo "=== E: unknown BUILDTYPE: $BUILDTYPE" >&2; exit 1 ;;
        esac
    fi
    export VYOS1X_REPO_URL=https://github.com/psleng/vyos-1x
    export VYOS1X_REPO_BRANCH=psl-master
    sudo --preserve-env=VYOS1X_REPO_URL,VYOS1X_REPO_BRANCH \
        ./build-vyos-image $BUILDFLAVOUR --architecture $ARCH --build-by "psleng@perle.com"
    cd -
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi
cd $ROOTDIR


############## ti-evm-fs-build
# This will populate ./build/fs/
TSK=ti-evm-fs-build
BLT=.filesystem.$TSK.built
if [ "$BUILDTARG" = "x86_64" ]; then
    # Not TI.
    echo "=== I: $0: Skipping $TSK because $BUILDTARG = x86_64"
    touch $BLT
fi

if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    # NOTE: for any non-architecture specific mods, do them here:
    #
    #   vyos-build/data/live-build-config/hooks/live/99-PSL-customize.chroot
    #
    # Changes made there will end up in the .iso

    # Check ISO file
    LIVE_IMAGE_ISO=vyos-build/build/live-image-$ARCH.hybrid.iso

    if [ ! -e ${LIVE_IMAGE_ISO} ]; then
      echo "=== E: $0: File ${LIVE_IMAGE_ISO} does not exist."
      exit 1
    fi

    ISOLOOP=$(sudo losetup --show -f ${LIVE_IMAGE_ISO})
    echo "Mounting iso on loopback: ${ISOLOOP}"

    ISO_DIR=$ROOTDIR/build/tmp
    sudo rm -rf build
    sudo mkdir -p  $ISO_DIR
    sudo mount -o ro ${ISOLOOP} $ISO_DIR
    FS=$ROOTDIR/build/fs
    sudo unsquashfs -d $FS $ISO_DIR/live/filesystem.squashfs

    # -rm -rf $FS/boot/grub
    sudo mkdir $FS/boot/dtb
    sudo cp -R $FS/usr/lib/linux-image*/* $FS/boot/dtb

    echo "=== I: $0: $TSK: Almost done; performing fs fixups"
    ## For debugging: stash the unsullied rootfs for later diffing via:
    ##  sudo diff -r --no-dereference fs fs.pristine 2>&1 | less
    #test -d $FS.pristine || { echo HACK; sudo cp -pr $FS $FS.pristine; }

    # Run the debian-live config scripts now within chroot of the fs.
    # This is a bit bogus but saves bootup time of the eventual product.
    sudo cp -p updates/run-live-config $FS/usr/lib/live/
    sudo chroot $FS bash -c usr/lib/live/run-live-config

    # Copy the perle-init once service that performs /lib/live/boot/* tasks
    sudo cp updates/perle-init.service $FS/lib/systemd/system
    sudo ln -s /lib/systemd/system/perle-init.service $FS/etc/systemd/system/multi-user.target.wants/perle-init.service
    sudo cp updates/perle-init.sh $FS/usr/bin
    # NOTE: model-info (default-config/cli-remove) is no longer installed here.
    # Per-model definitions now live in vyos-build data/models/<platform>/<name>/
    # and are resolved at boot by vyos.system.model (see vyos-1x
    # src/init/vyos-router). The old placeholder configs were removed.
    #
    # NOTE: /etc/product.env is intentionally NOT shipped here anymore. Board
    # identity comes from the EEPROM text blob that U-Boot injects onto the
    # kernel cmdline (prod_id=/model=), with /mnt/efi/product.env as the runtime
    # fallback. Copying a hardcoded updates/product.env stamped every image as a
    # single SKU (IOLAN-2A01), so boards without an EEPROM (e.g. the EVM)
    # misidentified. The build must not bake a fixed identity into the FS.

    if [ "$BUILDTYPE" = "bookworm-am64xx-igos" ]; then
        # Copy for early-gpio-init service
#        sudo cp updates/perle_gpio_map.py $FS/usr/local/bin
#        sudo cp updates/perle_gpioctl.py $FS/usr/local/bin
#        sudo cp updates/early-gpio-init.service $FS/etc/systemd/system
#        sudo ln -s /etc/systemd/system/early-gpio-init.service $FS/etc/systemd/system/sysinit.target.wants/early-gpio-init.service

        sudo cp updates/check-rtc-lsm.sh $FS/usr/local/bin
#        sudo cp updates/rtc-init.service $FS/etc/systemd/system
#        sudo ln -s /etc/systemd/system/rtc-init.service $FS/etc/systemd/system/sysinit.target.wants/rtc-init.service
    fi

    # add EFI (FAT) mount point /mnt/efi to /dev/mmcblk0p2 so system can access uEnv.txt and product.env
    echo "/dev/mmcblk0p2  /mnt/efi  vfat  defaults,nofail  0  2" | sudo tee -a $FS/etc/fstab

    # Decompress the vmlinuz (symlink to the real thing) into Image
    gunzip < $FS/boot/vmlinuz | sudo sh -c "cat > $FS/boot/Image"

    sudo umount -d build/tmp/
    sudo rm -rf build/tmp/

    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi


echo "=== I: $0: COMPLETED"
