#!/bin/bash
set -ex

# Check if the --repo parameter is provided
if [ "$#" -lt 2 ] || [ "$1" != "--repo" ]; then
    echo "Usage: $0 --repo <repository_url> [--clean]"
    exit 1
fi

ARCH=$(dpkg-architecture -qDEB_HOST_ARCH)

REPPREFIX_URL="$2"
REPO_URL_TI_DEB="$REPPREFIX_URL/debian-repos"
REPO_NAME="vyos-build"
REPO_URL="$REPPREFIX_URL/$REPO_NAME"
ROOTDIR=$(pwd)

. $ROOTDIR/.defs.mk

# Check if the --clean parameter is provided
CLEAN=false
if [ "$#" -eq 3 ] && [ "$3" == "--clean" ]; then
    CLEAN=true
fi

# Delete the repository if it already exists and --clean is specified
if [ -d "$REPO_NAME" ]; then
    if [ "$CLEAN" = true ]; then
        echo "Cleaning up existing repository $REPO_NAME."
        sudo rm -rf "$REPO_NAME"
        rm -f .filesystem.* # Also remove all intermediate targets
    else
        echo "Repository $REPO_NAME already exists. Skipping clone."
    fi
fi

# Clone the repository if it doesn't exist or was cleaned
if [ ! -d "$REPO_NAME" ]; then
    git clone -b psl-master --single-branch "$REPO_URL"
fi

# Copy package-build-iGOS/ to vyos-build/scripts/ now that it's there
SRCDIR=package-build-iGOS
DSTDIR=vyos-build/scripts/
if [ ! -d $DSTDIR/$SRCDIR ]; then
    echo "=== I: $0: Copying $ROOTDIR/$SRCDIR into $DSTDIR"
    cp -rf $SRCDIR $DSTDIR
    echo "These files were copied from $ROOTDIR/$SRCDIR" > $DSTDIR/$SRCDIR/README-PSL
    # Borrow the vyos-build build.py if package-build-iGOS had none
    BUILDPY=$DSTDIR/$SRCDIR/build.py
    if [ ! -f $BUILDPY ]; then
        echo "=== I: $0: Symlink VyOS build.py to $BUILDPY"
        ln -rvfs $DSTDIR/package-build/build.py $BUILDPY
    fi
    unset BUILDPY
fi

# Install build_flavor
cp -f $ROOTDIR/updates/arm64fs.toml $ROOTDIR/vyos-build/data/build-flavors/

#frr build fix need to be fixed up later on it the build process
export EMAIL="psleng@perle.com"

############## package-build
# This will populate ./vyos-build/scripts/package-build/
TSK=package-build
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: package-build.py $TSK BEGIN"
    ./package-build.py --dir $TSK --include \
        ethtool telegraf owamp net-snmp frr frr_exporter isc-kea strongswan \
        openvpn-otp aws-gwlbtun node_exporter blackbox_exporter \
        podman ddclient dropbear hostap kea keepalived netfilter \
        pmacct radvd isc-dhcp ndppd hsflowd pyhumps bash-completion \
        udp-broadcast-relay
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
fi


############## package-build-iGOS
# This will populate ./vyos-build/scripts/package-build-iGOS/
TSK=package-build-iGOS
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: package-build.py $TSK BEGIN"
    # See .defs.mk for $IGOS_PKGS value.
    # It is autogenerated from the IGOS_PKGS setting in Makefile
    ./package-build.py --dir $TSK --include $IGOS_PKGS
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
fi

############## package-build-iolan
# This will populate ./vyos-build/scripts/iolan_apps/
IOL_REPO_NAME="iolan_apps"
IOL_REPO_URL="git@github.com:Perle-Systems-Limited/iolan_apps.git"
TSK=iolan_apps
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: package-build.py $TSK BEGIN"

    if [ ! -d "vyos-build/scripts/$IOL_REPO_NAME" ]; then
        git clone -b main --single-branch "$IOL_REPO_URL" vyos-build/scripts/$IOL_REPO_NAME
    fi

    cd vyos-build/scripts/$IOL_REPO_NAME
    ./all-build.py
    cd -
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP package-build.py $TSK ($BLT exists)"
fi

############## package-symlink-debs
# This will populate ./vyos-build/packages/ with .deb files
TSK=package-symlink-debs
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    # Symlink everything to the vyos-build/packages directory
    for a in $(find $ROOTDIR/vyos-build/scripts -type f -name "*.deb")\
             $ROOTDIR/ti-bdebstrap/*.deb
    do
        test -s "$a" || continue  # Skip zero length junk

        case "$a" in
        *libsnmp-dev_*64.deb)  # Needed for frr (despite -dev_ pattern)
            ;;
        *libvppinfra-dev*)  # Needed for vpp and vyos-1x
            ;;
        *vpp-dev_*64.deb)  # Needed for vpp and vyos-1x
            ;;
        *isc-kea-doc*)  # isc-kea insists on this
            ;;
        *-dev_*|*-dbg_*|*-doc_*|*-dbgsym_*)  # Unwanted general patterns
            continue
            ;;
        */_CPack_Packages/*.deb)  # .deb build artifacts (duplicates)
            continue
            ;;
        */accel-ppp_*.deb)  # Obsolete accel-ppp (replaced by accel-ppp-ng)
            continue
            ;;
        */hsflowd.deb|*/sflowovsd.deb)  # Not actually .deb
            continue
            ;;
        esac

        test -f "$a" || continue
        echo "Symlinking package: $a"
        ln -vrfs $a $ROOTDIR/vyos-build/packages/
    done
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi

############## ti-linux-firmware
# This will populate ./debian-repos/ and augment vyos-build/packages/
TSK=ti-linux-firmware
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    if [ "$BUILDTARG" != "ti-evm" ]; then
        echo "=== I: $0: SKIP $TSK (target $BUILDTARG != ti-evm)"
    else
        # this section needs some rework to clean up how this ti firmware is pulled.
        sudo rm -rf debian-repos
        git clone -b psl-master $REPO_URL_TI_DEB
        cd debian-repos

        # Determine the Debian distro to use
        DEB_SUITE=$(python3 -c "import toml; print(toml.load('$ROOTDIR/vyos-build/data/defaults.toml').get('debian_distribution', ''))")
        if test -z "$DEB_SUITE"; then
            echo "=== E: $0: Cannot determine debian_distribution"
            exit 1
        fi

        sudo DEB_SUITE=$DEB_SUITE ./run.sh ti-linux-firmware
        cd ${ROOTDIR}
        if [ "$BUILDTYPE" = "bookworm-am64xx-evm" ]; then
            ln -vrfs debian-repos/build/$DEB_SUITE/ti-linux-firmware/*64*.deb $ROOTDIR/vyos-build/packages/
        elif [ "$BUILDTYPE" = "bookworm-j7200-evm" ]; then
            ln -vrfs debian-repos/build/$DEB_SUITE/ti-linux-firmware/*j7200*.deb $ROOTDIR/vyos-build/packages/
        else
            echo "=== E: $0: Undefined BUILDTARG:BUILDTYPE ($BUILDTARG:$BUILDTYPE)"
            exit 1
        fi
        # end of section for rework
    fi
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi
cd ${ROOTDIR}


############## build-vyos-image
# This will populate ./vyos-build/build/
# The psleng.github.io git repo must be populated for this to work.
TSK=build-vyos-image
BLT=.filesystem.$TSK.built
if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"
    cd $ROOTDIR/vyos-build

    # PSL related keys needed within the chroot within the build container.
    # They get copied from here into the chroot.
    LB_ARCH=data/live-build-config/archives
    cp -f ../updates/psleng.key $LB_ARCH/psleng.key.chroot
    cp -f $LB_ARCH/vyos-dev.pref.chroot $LB_ARCH/psleng.pref.chroot

    if [ "$BUILDTARG" = "x86_64" ]; then
        BUILDFLAVOUR=generic
    else
        BUILDFLAVOUR=${ARCH}fs
    fi
    export VYOS1X_REPO_URL=https://github.com/psleng/vyos-1x
    export VYOS1X_REPO_BRANCH=psl-master
    sudo --preserve-env=VYOS1X_REPO_URL,VYOS1X_REPO_BRANCH \
        ./build-vyos-image $BUILDFLAVOUR --architecture $ARCH --build-by "psleng@perle.com"
    cd -
    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi
cd $ROOTDIR


############## ti-evm-fs-build
# This will populate ./build/fs/
TSK=ti-evm-fs-build
BLT=.filesystem.$TSK.built
if [ "$BUILDTARG" != "ti-evm" ]; then
    # Not TI.
    echo "=== I: $0: Skipping $TSK because $BUILDTARG != ti-evm"
    touch $BLT
fi

if [ ! -f "$BLT" ]; then
    echo "=== I: $0: $TSK BEGIN"

    # NOTE: for any non-architecture specific mods, do them here:
    #
    #   vyos-build/data/live-build-config/hooks/live/99-PSL-customize.chroot
    #
    # Changes made there will end up in the .iso

    # Check ISO file
    LIVE_IMAGE_ISO=vyos-build/build/live-image-$ARCH.hybrid.iso

    if [ ! -e ${LIVE_IMAGE_ISO} ]; then
      echo "=== E: $0: File ${LIVE_IMAGE_ISO} does not exist."
      exit 1
    fi

    ISOLOOP=$(sudo losetup --show -f ${LIVE_IMAGE_ISO})
    echo "Mounting iso on loopback: ${ISOLOOP}"

    ISO_DIR=$ROOTDIR/build/tmp
    sudo rm -rf build
    sudo mkdir -p  $ISO_DIR
    sudo mount -o ro ${ISOLOOP} $ISO_DIR
    FS=$ROOTDIR/build/fs
    sudo unsquashfs -d $FS $ISO_DIR/live/filesystem.squashfs

    # -rm -rf $FS/boot/grub
    sudo mkdir $FS/boot/dtb
    sudo cp -R $FS/usr/lib/linux-image*/ti $FS/boot/dtb

    echo "=== I: $0: $TSK: Almost done; performing fs fixups"
    ## For debugging: stash the unsullied rootfs for later diffing via:
    ##  sudo diff -r --no-dereference fs fs.pristine 2>&1 | less
    #test -d $FS.pristine || { echo HACK; sudo cp -pr $FS $FS.pristine; }

    # Run the debian-live config scripts now within chroot of the fs.
    # This is a bit bogus but saves bootup time of the eventual product.
    sudo cp -p updates/run-live-config $FS/usr/lib/live/
    sudo chroot $FS bash -c usr/lib/live/run-live-config

    # Copy the perle-init once service that performs /lib/live/boot/* tasks
    sudo cp updates/perle-init.service $FS/lib/systemd/system
    sudo ln -s /lib/systemd/system/perle-init.service $FS/etc/systemd/system/multi-user.target.wants/perle-init.service
    sudo cp updates/perle-init.sh $FS/usr/bin
    sudo cp -rf updates/model-info $FS/usr/share/vyos/
    sudo cp -rf updates/product.env $FS/etc/

    # !!!! end of core rootfs fixups - do not add further fixups after this point
    # unless it is sdcard or mmc rootfs specific

    # START - make a copy of the ISO for squashfs image type
    STAGE_ISO=$ROOTDIR/build/stage_iso
    ISOPATH_BUILD=$ROOTDIR/iso-images/$BUILDTYPE

    # create directory for staging the squashfs version of the image
    sudo rm -rf $STAGE_ISO
    sudo mkdir -p $STAGE_ISO
    sudo chmod u+w $STAGE_ISO

    # copy entire ISO to staging area,  preserving all attrs, hidden, symlinks
    # and remove original filesystem.squashfs in prep for updated one
    sudo cp -a $ISO_DIR/. $STAGE_ISO/
    sudo rm -f $STAGE_ISO/live/filesystem.squashfs

    # copy all cumulative fixups in flat rootfs preserving all attrs, hidden, symlinks
    # to the staging filesystem directory

    # copy the dtbs from built location to /boot/dtb for uboot to access this is different
    # than copying it WITHIN the /boot/dtb in the LINUX rootfs that install_image.py needs
    # to copy to another image's /boot/dtb that uboot needs to access
    sudo mkdir $STAGE_ISO/boot/dtb
    sudo cp -R $FS/usr/lib/linux-image*/ti $STAGE_ISO/boot/dtb

    SQUASHFILE=$STAGE_ISO/live/filesystem.squashfs
    # now we need to squash everthing back to the /live/filesystem.squashfs and zap the rest of the rootfs
    # except for what was in the original ISO
    sudo mksquashfs $FS $SQUASHFILE -comp xz -b 262144 -always-use-fragments -noappend

    # we need to replace the sha256 checksum, in the live/sha256sum.txt as the last thing, otherwise
    # the "add system image <file.iso> will fail on checksum verificatiom
    SHA256TXTFILE=$STAGE_ISO/sha256sum.txt
    RELSQUASHFILE=./live/filesystem.squashfs

    # make the sha256sum.txt writeable
    sudo chmod u+w $SHA256TXTFILE

    # Calculate new hash
    NEWHASH=$(sha256sum "$SQUASHFILE" | awk '{print $1}')

    # Update the entry inside sha256sum.txt
    sudo sed -i "s|^[0-9a-f]\{64\}  $RELSQUASHFILE|$NEWHASH $RELSQUASHFILE|" "$SHA256TXTFILE"

    # make the sha256sum.txt non-writeable
    sudo chmod u-w $SHA256TXTFILE

    # Extract the kernel version from the initrd.img-* file (assuming it follows the pattern)
    KERNEL_VER=$(ls ${STAGE_ISO}/live/initrd.img-* | sed 's/.*initrd.img-\(.*\)/\1/' | head -n 1)

    echo "Creating initrd.img-${KERNEL_VER} and vmlinuz-${KERNEL_VER} symlinks"

    # Create the symlinks
    sudo ln -sf initrd.img-${KERNEL_VER} ${STAGE_ISO}/live/initrd.img
    sudo ln -sf vmlinuz-${KERNEL_VER} ${STAGE_ISO}/live/vmlinuz

    # cleanup the staging filesystem directory
    sudo rm -rf $ISOPATH_BUILD/stage_iso
    sudo mkdir -p $ISOPATH_BUILD/stage_iso
    sudo cp -a $STAGE_ISO/. $ISOPATH_BUILD/stage_iso/
    sudo rm -rf $STAGE_ISO

    # END - make a copy of the rootfs for non-sdcard image

    # housekeeping - remove vyos-build/build/vyos*.iso
    sudo rm -f vyos-build/build/vyos*.iso

    # flat rootfs sdcard build continues below

    # Decompress the vmlinuz (symlink to the real thing) into Image
    gunzip < $FS/boot/vmlinuz | sudo sh -c "cat > $FS/boot/Image"

    sudo umount -d build/tmp/
    sudo rm -rf build/tmp/

    touch "$BLT" # build success
else
    echo "=== I: $0: SKIP $TSK ($BLT exists)"
fi


echo "=== I: $0: COMPLETED"
