#
# Make PSL VyOS
#
# This attempts to encapsulate the README.md steps,
# except for the final writing to uSDcard.
#

# Do not use implicit rules or variables to reduce confusion
MAKEFLAGS += -rR

# Build definitions.  Contents should be VAR=val format
# so that it can also be sourced by shell scripts.
DEFS := .defs.mk
ifeq ($(wildcard $(DEFS)),)
else
include $(DEFS)
endif

# Quasi targets
CONT_TARG     = .cont.built
KERNEL_TARG   = .kernel.built
UBOOT_TARG    = .uboot.built
FS_TARG       = .filesystem.built
IMAGE_TARG    = .image.built
ISO_TARG      = .iso.built

DATECODE := $(shell date +%Y%m%d%H%M%S00)

.PHONY: help all test sdcard sdcard-squashfs live-iso dfuimg status clean mostlyclean targ-ti-am64x targ-ti-j7200 targ-x86 containerclean spotless prod-image

help:
	@echo First select a build type.  Valid types are:
	@echo
	@echo '    make targ-perle-iolan # Perle AM64x IOLAN board'
	@echo '    make targ-ti-am64x    # TI AM64x evaluation module'
	@echo '    make targ-ti-j7200    # TI J7200 evaluation module'
	@echo '    make targ-x86         # x86'
	@echo
	@echo 'Then type "make all".  Type "make clean" for a clean start.'
	@echo 'You will have to reselect the build type after doing that.'
	@echo
	@echo 'Type "make status" to see the current state of the build'
	@echo 'and potential build issues.'
	@echo
	@echo 'There are various clean targets.  From most to least destructive:'
	@echo
	@echo 'make spotless       # like "make clean containerclean"'
	@echo 'make clean          # like "make mostlyclean" but also images/'
	@echo 'make mostlyclean    # clean build artifacts'
	@echo 'make containerclean # remove build container image.'
	@echo
	@echo 'make sdcard         # flash sdcard with the built image'
	@echo 'make sdcard-squashfs# flash sdcard with squash image in ./iso-images<buildtype/stage-iso'
#	@echo 'make live-iso       # create iso in ./iso-images/<buildtype>'
	@echo 'make dfuimg         # create DFU images to \"dfu-images\" folder'
	@echo 'make prod-image     # create 16G emmc and boot images in ./iso-images/<buildtype>'
	@echo
	@if [ -s "$(DEFS)" ]; then \
	    echo "The current build settings ($(DEFS)) are:"; \
	    cat $(DEFS); \
	fi

# List of iGOS packages to build.
# This is used in build_iGOS_TMDS64EVM_fs.sh and others.
#IGOS_PKGS='flask-react-web apnscripts psl-progs saml-sso vyos-1x vyatta-bash vyos-user-utils \
#           vyatta-biosdevname vyatta-cfg vyos-http-api-tools \
#           ipaddrcheck hvinfo libgpiod \
#           libmnl libpam-radius-auth initramfs-tools libnss-mapuser \
#           ssh-tpm-agent tacacs live-boot tpm2-openssl'
IGOS_PKGS='vyos-1x modemmanager'

# BUILDTYPE below is a builds entry from ti-bdebstrap/builds.toml
AUTOGEN=\# This file is autogenerated by Makefile. Do not edit.

# target build: Perle IOLAN board
targ-perle-iolan:
	@test `arch` = aarch64 || { echo "WARNING: building for this target on this machine (`arch`) is not supported" >&2; }
	@echo "$(AUTOGEN)" > $(DEFS)
	@echo BUILDTARG=perle-iolan >> $(DEFS)
	@echo BUILDTYPE=bookworm-am64xx-iolan >> $(DEFS)
	@echo IGOS_PKGS="$(IGOS_PKGS)" >> $(DEFS)

# target build: TI TMDS64EVM board
targ-ti-am64x:
	@test `arch` = aarch64 || { echo "WARNING: building for this target on this machine (`arch`) is not supported" >&2; }
	@echo "$(AUTOGEN)" > $(DEFS)
	@echo BUILDTARG=ti-evm >> $(DEFS)
	@echo BUILDTYPE=bookworm-am64xx-evm >> $(DEFS)
	@echo IGOS_PKGS="$(IGOS_PKGS)" >> $(DEFS)

# target build: TI J7200 board
targ-ti-j7200:
	@test `arch` = aarch64 || { echo "WARNING: building for this target on this machine (`arch`) is not supported" >&2; }
	@echo "$(AUTOGEN)" > $(DEFS)
	@echo BUILDTARG=ti-evm >> $(DEFS)
	@echo BUILDTYPE=bookworm-j7200-evm >> $(DEFS)
	@echo IGOS_PKGS="$(IGOS_PKGS)" >> $(DEFS)

# target build: x86_64
targ-x86:
	@test `arch` = x86_64 || { echo "WARNING: building for this target on this machine (`arch`) is not supported" >&2; }
	@echo "$(AUTOGEN)" > $(DEFS)
	@echo BUILDTARG=x86_64 >> $(DEFS)
	@echo IGOS_PKGS="$(IGOS_PKGS)" >> $(DEFS)


# Base repository to use for all container build recipes.
REPO := https://github.com/psleng

ARCH := $(shell dpkg-architecture -qDEB_HOST_ARCH)
# Different image tag for docker vyos/vyos-build image
ifeq ($(ARCH),arm64)
	IMGTAG := current-arm64
else
	IMGTAG := latest
endif

all: $(DEFS) $(ISO_TARG)

$(DEFS):
	@echo 'Error: no build type chosen.'
	@echo 'Type "make help" for instructions'
	@exit 1

test:
	@echo There are no tests in place at this time.

# Run a docker session.
define DOCKRUN
	@echo "### $$(date --iso-8601=s): Making $(1) using $(2) for target $@. Check $(1).ERR for status."
	stdbuf -i0 -oL -e0 ./rundocker.sh /bin/sh -c '$(2) --repo $(REPO)' 2>&1 | tee $(1).ERR
	@echo "### $$(date --iso-8601=s): Making $(1) using $(2) for target $@ COMPLETED"
	@touch $@
endef

# Build the arm64 VyOS building container image
$(CONT_TARG):
	@echo '### Making build container image ($@)'
	./buildvyoscontainer.sh
	@touch $@

# Build the kernel
$(KERNEL_TARG): $(CONT_TARG)
	@$(call DOCKRUN,kernel,./build_iGOS_TMDS64EVM_kernel.sh)

# Build u-boot (vyos-build/packages/u-boot_*.deb)
$(UBOOT_TARG): $(KERNEL_TARG)
	#
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
	@touch $@
else
	@$(call DOCKRUN,uboot,./buildiGOSti.sh $(BUILDTYPE) --ubootonly)
endif

# Build the root filesystem
$(FS_TARG): $(UBOOT_TARG)
	@$(call DOCKRUN,filesystem,./build_iGOS_TMDS64EVM_fs.sh)

# Create a uSDcard image
$(IMAGE_TARG): $(FS_TARG)
	#
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
	@echo "### The final .iso image should be here:"
	@ISO=vyos-build/build/live-image-$(ARCH).hybrid.iso; if [ -f $$ISO ]; then ls -l `realpath $$ISO`; else echo "Error: $$ISO not found!"; fi
	@touch $@
else
	@echo '### Making uSDcard image'
# This invalid directory sometimes appears breaking git ops on build
	@if [ -d ~root/.gitconfig ]; then sudo rm -rf ~root/.gitconfig; fi
	@$(call DOCKRUN,image,./buildiGOSti.sh $(BUILDTYPE))
	@touch $@
endif

# Create a iso image
$(ISO_TARG): $(IMAGE_TARG)
	#
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
	@echo "### The final .iso image should be here:"
	@ISO=vyos-build/build/live-image-$(ARCH).hybrid.iso; if [ -f $$ISO ]; then ls -l `realpath $$ISO`; else echo "Error: $$ISO not found!"; fi
	@touch $@
else
	@echo '### Making ISO image'
	@$(call DOCKRUN,iso,./buildiGOS_iso.sh $(BUILDTYPE))
	@command -v xorriso >/dev/null 2>&1 || { \
		echo "Warning: xorriso is not installed....installing it now"; \
		sudo apt-get install -y -qq xorriso; \
	}
	# create an iso with the igos updates using the same iso attributes
	sudo xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes -iso-level 3 -A "iGOS" \
  -p "live-build ${DATECODE}; https://salsa.debian.org/live-team/live-build" \
  -publisher "psleng@perle.com" -V "iGOS" --modification-date="${DATECODE}" \
  -e boot/grub/efi.img -no-emul-boot -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
  -o iso-images/$(BUILDTYPE)/"igos-live-${DATECODE}-arm64.iso" iso-images/$(BUILDTYPE)/stage_iso

	@ls -l images/$(BUILDTYPE)/tisdk*.squashfs
	@echo '### '
	@echo '### Making uSDcard image COMPLETED'
	@echo '### Type "bin/buildlog" to check for errors'
	@echo '### '
	@echo '################################################################################# '
	@echo '### Type "make sdcard" to write bootloader and flat rootfs to an uSD card'
	@echo '### Type "make sdcard-squashfs" to write bootloader + squashed rootfs to uSD card'
#	@echo '### Type "make live-iso" to create a live iso under /iso_images'
	@echo '### Type "make prod-image" to create 16G emmc and boot images in /iso-images'
	@echo '################################################################################# '
	@echo '#### '
	@echo '######################################################## '
	@echo '### List of ISO images in iso-images/$(BUILDTYPE)'
	@echo '######################################################## '
	@ls -l iso-images/$(BUILDTYPE)/*.iso
	@echo '### '
	@echo '### Making ISO image COMPLETED'
	@echo '### '
	@touch $@
endif

# Write bootloader and flat rootfs to a uSDcard.
sdcard: $(IMAGE_TARG)
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
else
	@echo '### Making $@'
	sudo ti-bdebstrap/create-sdcardiGOS.sh $(BUILDTYPE)
	@echo '### Making $@ COMPLETED'
endif

# Write bootloader and squashfs rootfs to a uSDcard.
sdcard-squashfs: $(IMAGE_TARG)
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
else
	@echo '### Making $@'
	sudo ti-bdebstrap/create-sdcardiGOS.sh $(BUILDTYPE) squashfs
	@echo '### Making $@ COMPLETED'
endif

# Create a live ISO from the iso_image/$(BUILDTYPE)/stage_iso/*
live-iso: $(IMAGE_TARG)
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
else
	@echo '### Making $@'
	@command -v xorriso >/dev/null 2>&1 || { \
		echo "Warning: xorriso is not installed...installing now"; \
		sudo apt-get install -y -qq xorriso; \
	}
	# create an iso with the igos updates using the same iso attributes
	sudo xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes -iso-level 3 -A "iGOS" \
  -p "live-build ${DATECODE}; https://salsa.debian.org/live-team/live-build" \
  -publisher "psleng@perle.com" -V "iGOS" --modification-date="${DATECODE}" \
  -e boot/grub/efi.img -no-emul-boot -isohybrid-gpt-basdat -isohybrid-apm-hfsplus \
  -o iso-images/$(BUILDTYPE)/"igos-live-${DATECODE}-arm64.iso" iso-images/$(BUILDTYPE)/stage_iso

	@echo '### Making $@ COMPLETED'
endif

# Create DFU Images.
dfuimg: $(IMAGE_TARG)
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
else
	@echo '### Making $@'
	@./build-dfu-image.sh
	@echo '### Making $@ COMPLETED'
endif

# Create emmc and boot production .img files.
prod-image: $(IMAGE_TARG)
ifeq ($(BUILDTARG),x86_64)
	@echo "### Skipping $@ because BUILDTARG=$(BUILDTARG)"
else
	@echo '### Making $@'
	@./build_igos_prod_image.sh
	@echo '### Making $@ COMPLETED'
endif

# View state of build
#
# The ad-hoc "error checking" below looks for possible fatal/error failures
# ignoring ones known to be harmless.
#
status:
	@ls -ltr .*built 2> /dev/null || echo This working tree is clean
	@echo; if [ -f $(IMAGE_TARG) ]; then \
	 echo The build appears to be complete!;\
	 else echo The build appears INCOMPLETE; fi
	@echo; echo "For more details type:\n\t./bin/buildlog"

# Clean everything including container image.
spotless: clean containerclean

# Clean everything.
clean: mostlyclean
	sudo rm -rf images dfu-images iso-images

# Clean build artifacts only (but not built images).
mostlyclean:
	rm -f *.ERR .*.built $(DEFS)
	sudo rm -rf vyos-build build debian-repos ti-bdebstrap drivers logs tools configs scripts builds.toml create-sdcardiGOS.sh

# Clean the container image.  It rarely needs rebuilding.
containerclean:
	docker image rm vyos/vyos-build:$(IMGTAG) || true
	@echo 'Cleaning up docker garbage. This could take several minutes.'
	docker system prune -f
