#!/bin/bash
#
# Create git repository server for testing.
#

PROG=$(basename $0)
if [ ! -d work ]; then
    echo "$0: No work directory.  Run ./merge-from-upstream first" >&2
    exit 1
fi

# We use a copy to guarantee that we do not accidentally make changes in
# the source "work" directory, which is what is targeted for upstream push.
WORK=$PWD/work.copy
REPODIR=$WORK/.REPO
PIDFILE=$WORK/$PROG.pid
LOG=$WORK/$PROG.out

killdaemon()
{
    if [ -f "$PIDFILE" ]; then
        echo "*** Killing git server daemon"
        kill $(<$PIDFILE) > /dev/null 2>&1 || true
        rm -f $PIDFILE
        sleep 1
    fi
}

case "$1" in

stop)
    echo "*** Stopping server and cleaning up"
    killdaemon
    rm -rf $REPODIR git-daemon-export-ok $LOG $WORK
    exit 0
    ;;

status)
    if [ -f "$PIDFILE" ]; then
        kill -0 $(cat $PIDFILE) > /dev/null 2>&1 && {
            IP=$(ip route show default | sed 's/.*src \([0-9.]*\) .*/\1/')
            echo "Running.  Clone via:"
            echo "   git clone git://$IP/vyos-build"
            echo "Logfile is $LOG"
        }
    else
        echo Not running
    fi
    exit 0
    ;;

'')
    ;;

*)
    echo Usage: "$0 [stop|status]" >&2
    exit 1
    ;;
esac

echo "*** Copying the precious work directory to $WORK..."
rm -rf $WORK
cp -pr work $WORK
cd $WORK

mkdir -p $REPODIR

# Set up all the repos
for repo in *
do
    # test $REPO = $REPODIR && continue
    test -d $repo || continue

    REPOGIT=$REPODIR/$repo.git
    test -d $REPOGIT && continue # already here

    #echo "*** Copying $repo/.git to $REPOGIT ..."
    #cp -pr $repo/.git $REPOGIT
    echo "*** Making bare copy of $repo to $REPOGIT"
    (
        cd $REPODIR
        git clone --mirror --no-hardlinks ../$repo
        cd $repo.git
        git config --bool daemon.receivepack true
        # git config --bool core.bare true
        # # See --enable=receive-pack below
        git config receive.denyCurrentBranch ignore
        # git lfs install
        git fetch --all
    )
done

# Cannot use localhost for git clone as it is mostly done in containers.
# Try to figure out our routable address.
IP=$(ip route show default | sed 's/.*src \([0-9.]*\) .*/\1/')
echo
echo "Example for cloning:"
echo
echo "   git clone git://$IP/vyos-build" | tee $LOG
echo
echo "You can hack the ../package-build-iGOS/*/package.toml files"
echo "files mentioned in work/TODO to use that URL form"

cd $REPODIR
touch git-daemon-export-ok # Allow exports
killdaemon

# Enable push.  This is NOT secure, but means we can push temporary hacks
# to the $WORK/.REPO copy (git://10.x.x.x/) for the sake of test builds.
# Such pushed changes will NOT end up at github.com/psleng since it is
# being made to a local copy of the source "work" directory which is what
# will actually be pushed.
EXTRAOPTS=--enable=receive-pack

git daemon --reuseaddr --export-all $EXTRAOPTS --base-path=$PWD --verbose --pid-file=$PIDFILE $PWD 2>&1 | tee $LOG &
