#!/usr/bin/python3
'''
This supports multiple functions depending on the invoked name(see __main__).

merge-from-upstream: Merge from upstream for all iGOS packages.
tomldiff: Compare iGOS package.toml to the VyOS ones (post merge-from-upstream)
'''
import sys
import os
import textwrap
from subprocess import run, CompletedProcess
from pathlib import Path
try:
    import tomli
except ModuleNotFoundError:
    os.system('sudo apt install python3-tomli')
    import tomli


# All the repository merging takes place under this directory.
WORKDIR = 'work'

# Helpful instructions
TODO = Path(WORKDIR, 'TODO')


def findup(targ: str) -> (Path | None):
    '''
    Look upwards from the current directory until a file or
    directory "targ" is found.  Returns resulting path or None
    '''
    dirpath = Path('.')
    root = Path('/')
    while dirpath.resolve() != root:
        dst = Path(dirpath, targ)
        if dst.exists():
            return dst
        dirpath = dirpath.joinpath('..')
    return None


def merge_from_upstream(dpkg: dict) -> (str | None):
    '''
    Do the merge from upstream work.
    '''
    def dump(pfx: str, r: CompletedProcess) -> None:
        '''Helper for printing process output'''
        for i in (r.stdout, r.stderr):
            if i:
                sys.stdout.write(pfx + ' ' + i.decode())

    workdir = Path(WORKDIR, dpkg['name'])
    if os.path.exists(workdir):
        print(f' I: directory "{workdir}" already exists; skipping')
        return str(workdir)

    name = dpkg['name']
    url = dpkg['scm_url']

    # We *could* use the python "git" module here, but it is likely
    # easier for humans to understand what is going on by using
    # git cli directly.

    # Clone ours (psleng)
    if 'psleng' not in url:
        print(f' W: Cannot merge {url} for {name} because'
              ' it is not a psleng repo')
        return None

    print(f' I: Cloning {url} for {name}')
    run(['git', 'clone', '-q', url, workdir], check=True)
    # commit = dpkg['commit_id']
    # print(f' I: Checkout commit_id {commit} for {name}')
    # run(['git', 'checkout', '-q', commit], cwd=workdir, check=True)

    cwd = os.getcwd()
    try:
        os.chdir(workdir)
        # Add the corresponding upstream, defaulting to vyos
        upstream = dpkg.get('scm_url_upstream',
                            f'https://github.com/vyos/{name}.git')

        run(['git', 'remote', 'add', 'upstream', upstream], check=True)
        run(['git', 'fetch', '-q', '--tags', '--all'], check=True)
        r = run(['git', 'branch', '--show-current'],
                capture_output=True, check=True)
        origbranch = r.stdout.decode().strip()
        print(f' I: Default branch is {origbranch}')

        # Decide on the name of the upstream branch.
        # Use upstream_branch from toml if provided, else
        # prefer "current" if available remotely, otherwise use existing.
        # This happens for packages like libmnl
        branch = dpkg.get('upstream_branch', 'current')
        if branch != 'current':
            print(f' I: toml suggests {branch} as upstream branch')
        r = run(['git', 'branch', '--list', '--remotes'],
                capture_output=True, check=True)
        if f'upstream/{branch}' not in r.stdout.decode():
            # Use existing psleng branch if upstream has it
            print(f' I: Cannot find upstream/{branch}')
            r = run(['git', 'branch', '--show-current'],
                    capture_output=True, check=True)
            branch = r.stdout.decode().strip()
            if branch == 'psl-master':
                # Will not exist upstream.  Pick master or first upstream.
                upstreams = os.listdir('.git/refs/remotes/upstream')
                print(f' I: available upstream branches: {upstreams}')
                if 'master' in upstreams:
                    branch = 'master'
                else:
                    branch = upstreams[0]
            print(f' I: Using {branch} as the upstream')

        # Make the branch if not already in place
        if not Path(f'.git/refs/heads/{branch}').exists():
            print(f' I: No "{branch}" branch; making it')
            r = run(['git', 'checkout', '-q',
                     '--track', f'origin/{branch}'],
                     capture_output=True)
            dump('  N:', r)
            if r.returncode:
                branch = dpkg.get('upstream_branch', 'current')
                print(f' I: Failed; falling back to {branch}')
            else:
                origbranch = branch

        if branch == 'psl-master':
            # No branch found
            print(' E: Cannot find a reasonable upstream branch to merge')
            exit(1)

        # Finally, do the merge from upstream
        print(f' I: Merging from upstream/{branch} into {origbranch}')
        r = run(['git', 'merge', '-q', '--no-commit', f'upstream/{branch}'],
                capture_output=True, check=True)
        dump('  N:', r)
        print(' I: Merge succeeded!')

    finally:
        os.chdir(cwd)

    return str(workdir)


################################

# Find top level directory
topdir = findup('.git')
if not topdir:
    raise FileNotFoundError('.git')

topdir = topdir.parent

# .defs.mk should be there
defsmk = topdir.joinpath('.defs.mk')
if not Path(defsmk).exists():
    print('E: Cannot locate .defs.mk')
    exit(1)

# Parse IGOS_PKGS from .defs.mk
igos_pkgs = []
with open(defsmk) as fp:
    for i in fp.readlines():
        if not i.startswith('IGOS_PKGS'):
            continue
        # Take value portion, remove leading/trailing "'", listify
        igos_pkgs = i.split('=', 1)[-1].strip().strip("'").split()

if not igos_pkgs:
    print(f'E: Cannot find IGOS_PKGS in {defsmk}')
    exit(1)
igos_pkgs.sort()

# The directory containing packages with package.toml files
IGOSPATH = Path(topdir, 'package-build-iGOS')


def do_merge() -> None:
    '''Do the merge from upstream task'''
    # Create the new workdir
    if Path(WORKDIR).exists():
        print(f'E: Directory "{WORKDIR}" already exists from a previous run.')
        print('E: Examine it and either push the changes in it or remove it.')
        if TODO.exists():
            print(f'E: See the file "{TODO}" for instructions')
        exit(1)
    os.mkdir(WORKDIR)

    # Try to merge from upstream all the repos listed in the packages
    workdirs = []
    for pkg in igos_pkgs:
        print(f'\nI: Processing {pkg}')

        pkgtoml = Path(IGOSPATH, pkg, 'package.toml')
        if not pkgtoml.exists():
            print(f'E: {pkgtoml} not found but is in {defsmk}!')
            exit(1)

        # Parse the toml
        toml = tomli.load(open(pkgtoml, 'rb'))
        pkgs: dict = toml['packages']
        for dpkg in pkgs:
            d = merge_from_upstream(dpkg)
            if d:
                workdirs.append(d)

    # Special cases: vyos-build (does not use package.toml).
    #
    # Also vyos1x-config and vyconf which are explicitly referred
    # to by libvyosconfig/build.sh .  We use the default branch
    # as commit_id for these so the merge happens to the correct place.
    # The above build.sh uses a commit hash so the psl-master
    # does not actually get used.
    #
    # Cook up what the parsed package.toml parts would look like.
    print('\nI: Processing extra packages (no package.toml)')
    extrapkgs = (
        {'name': 'vyos-build',
         'scm_url': 'git@github.com:psleng/vyos-build',
         'commit_id': 'psl-master'},
        {'name': 'vyos1x-config',
         'scm_url': 'git@github.com:psleng/vyos1x-config',
         'commit_id': 'current'},
        {'name': 'vyconf',
         'scm_url': 'git@github.com:psleng/vyconf',
         'commit_id': 'master'}
    )
    for dpkg in extrapkgs:
        print(f'\nI: Processing {dpkg["name"]}')
        d = merge_from_upstream(dpkg)
        if d:
            workdirs.append(d)

    # It all worked.  Print a list of directories needing
    # to be committed/pushed.
    topush = []
    for workdir in workdirs:
        if Path(workdir, '.git', 'MERGE_HEAD').exists():
            topush.append(workdir)

    print('==============')
    if topush:
        # Output hopefully helpful instructions.
        txt = f'''
            For each, the manual procedure is:

            1. "cd <targetdir>"
            2. "git commit"
            3. "git branch"
            4. "git switch <psl-master or whatever the above shows>"
            5. "git merge <current or whatever the source branch was>"
            6. On merge conflicts, fix them and do "git commit"

            After this you should test that the build still works.
            If all looks good you can do "push --all" in each of the above.
            Note: You *MUST* use the "--all" flag so that all branches push!

            To do the push you will have to edit .git/config
            and change the url from the form:

                https://github.com/psleng/XXX

            to:

                git@github.com:psleng/XXX

            WARNING: before doing this, make sure that VyOS actually has
            a working daily build or you will be pulling broken code!

            Look here:

            \thttps://vyos.net/get/nightly-builds/

            NOTE: you should then manually examine all package.toml files under
            {IGOSPATH} to see if they have changed on the VyOS side.

            \tvyos-build/scripts/package-build

            The program ./tomldiff is helpful for this task.

            NOTE: See also the repo-maintenance/README.md for more hints,
            such as running a local gitserver for testing before pushing.'''
        # Write to TODO
        with open(TODO, 'w') as fp:
            print(f'The following directories in {WORKDIR} need to be'
                  ' committed\nand eventually pushed via "push --all":\n',
                  file=fp)
            for i in topush:
                print(f'\t{os.path.basename(i)}', file=fp)
            print(textwrap.dedent(txt), file=fp)
        # Echo that stdout
        with open(TODO) as fp:
            print(fp.read())
        print(f'(The above info can be found in {TODO})')
    else:
        print('No changes needs to be committed/pushed.')


def dodiff(diff: str, igos_toml: Path, vyos_toml: Path) -> None:
    'Perform a diff using given tool'
    sys.stdout.flush()
    os.system(f'{diff} {igos_toml} {vyos_toml}')
    sys.stdout.flush()


def do_tomldiff() -> None:
    '''Do a toml diff'''
    if not Path(WORKDIR).exists():
        print(f'ERROR: {WORKDIR} does not exist', file=sys.stderr)
        print('You need to run ./merge-from-upstream first', file=sys.stderr)
        exit(1)

    # A bit crude.  If any argument provided, use vimdiff instead of diff
    if len(sys.argv) > 1:
        diff = 'vimdiff'
    else:
        diff = 'diff'

    missingdir: list[Path] = []
    missingtoml: list[Path] = []
    TOML = Path('package.toml')
    igos_path = Path('../package-build-iGOS')
    # vyos_path = Path('../vyos-build/scripts/package-build')
    vyos_path = Path(f'{WORKDIR}/vyos-build/scripts/package-build')

    # For each iGOS package, compare the package.toml with VyOS's
    for pkg in igos_pkgs:
        igos_toml = Path(igos_path, pkg, TOML)
        vyos_dir = Path(vyos_path, pkg)
        vyos_toml = Path(vyos_dir, TOML)

        print(f'================= {pkg}')
        if not igos_toml.exists():
            raise FileNotFoundError(igos_toml)

        if not vyos_dir.exists():
            missingdir.append(vyos_dir)
            continue

        if not vyos_toml.exists():
            missingtoml.append(vyos_toml)
            continue

        dodiff(diff, igos_toml, vyos_toml)

    #
    # Special case for Dockerfile if merge-from-upstream has been done.
    # This is not .toml, but we really do not want to miss changes here!
    #
    print('================= file Dockerfile-aarch64')
    dockerfile = Path(f'{WORKDIR}/vyos-build/docker/Dockerfile')
    if dockerfile.exists():
        dodiff(diff, dockerfile, Path('../Dockerfile-aarch64'))
    else:
        print(f'(skipped because {dockerfile} missing)')

    if missingdir:
        # Probably means VyOS builds them manually on demand.
        print()
        print(f'The following directories are missing in {vyos_path}/')
        print(f'but exist in {igos_path}/ so there is no package.toml')
        print('to compare against.  It is likely that VyOS are building')
        print('these manually via "dpkg-buildpackage -uc -us -tc -b"')
        print()
        for p in missingdir:
            print(f'{p}/')

    if missingtoml:
        # VyOS has it but the build part is apparently disabled.
        print()
        print(f'The following package.toml files are missing in {vyos_dir}/')
        print(f'but exist in {igos_path}/')
        print('Should we even be building it?')
        print()
        for p in missingtoml:
            print(p)


if __name__ == '__main__':
    prog = Path(sys.argv[0]).stem
    if prog == 'merge-from-upstream':
        do_merge()
    elif prog == 'tomldiff':
        do_tomldiff()
    else:
        print(f'ERROR: do not know how to do "{prog}"', file=sys.stderr)
        exit(1)
