# Generic (aka "universal") ISO image

image_format = "iso"

# Include these packages in the image regardless of the architecture
packages = [
  # QEMU and Xen guest tools exist for multiple architectures
  # TODO - added python3-XXX pkgs temporarily for flask-react dependencies
  "qemu-guest-agent",
  "python3-pip",
  "python3-venv",
  # "tpm2-openssl",
  # "vyos-xe-guest-utilities",
]

[architectures.amd64]
  # Hyper-V and VMware guest tools are x86-only
  packages = ["hyperv-daemons", "vyos-1x-vmware"]
